# ========================================
# YOLOv8n-seg Training Configuration - TCC
# Segmentação de Datas de Validade
# ========================================
# Hardware: GTX 1660 Super (6GB VRAM)
# Dataset: ~1000 imagens
# Tempo estimado: 2-3 horas
# ========================================

# Data configuration
data: config/yolo/segmentation/data_seg.yaml

# Model configuration
model: yolov8n-seg.pt  # Nano Segmentation - modelo mais leve
task: segment

# Training hyperparameters
epochs: 100    # Épocas suficientes para dataset pequeno
imgsz: 640     # Resolução padrão YOLO
batch: 8       # Batch reduzido (segmentação usa mais memória)
device: 0      # GPU 0 (primeira GPU disponível)

# Learning rate schedule
lr0: 0.01      # Learning rate inicial
lrf: 0.01      # Learning rate final (fração do inicial)
momentum: 0.937
weight_decay: 0.0005

# Optimizer
optimizer: SGD  # SGD geralmente melhor que Adam para YOLO

# Training settings
patience: 50        # Early stopping após 50 épocas sem melhoria
workers: 4          # Número de workers (ajustado para Windows)
cache: false        # false = menos RAM, true = treinamento mais rápido
save: true          # Salvar checkpoints
save_period: -1     # -1 = salvar apenas o melhor modelo
exist_ok: true      # Sobrescrever experimentos anteriores

# Loss gains (pesos das losses)
box: 7.5   # Peso da loss de bounding box
cls: 0.5   # Peso da loss de classificação
dfl: 1.5   # Peso da loss de distribution focal

# Data augmentation (HABILITADO - crítico para dataset pequeno!)
augmentation: true

# Augmentations geométricas
hsv_h: 0.015        # Variação de matiz (hue)
hsv_s: 0.7          # Variação de saturação
hsv_v: 0.4          # Variação de brilho (value)
degrees: 10.0       # Rotação (±10 graus)
translate: 0.1      # Translação (10% da imagem)
scale: 0.5          # Zoom in/out (50%)
shear: 0.0          # Cisalhamento (desabilitado)
perspective: 0.0    # Distorção de perspectiva (desabilitado)
flipud: 0.0         # Flip vertical (0 = desabilitado - texto invertido)
fliplr: 0.5         # Flip horizontal (50% de chance)

# Augmentations avançadas
mosaic: 1.0         # Mosaic augmentation (combina 4 imagens)
mixup: 0.1          # MixUp (mistura 2 imagens) - 10% de chance
copy_paste: 0.0     # Copy-paste augmentation (desabilitado)

# Validation settings
val: true           # Executar validação durante treinamento
plots: true         # Gerar plots de métricas
rect: false         # Rectangular training (false = mais augmentation)

# Project settings
project: experiments              # Pasta onde salvar resultados
name: yolov8n-seg_validade       # Nome do experimento

# Inference settings
conf: 0.25          # Confidence threshold para predições
iou: 0.7            # IoU threshold para NMS

# ========================================
# Notas Importantes:
# ========================================
# • Segmentação usa mais memória que detecção
# • Batch menor que detecção (8 vs 16)
# • Tempo de treino ~30% maior que detecção
# • Dataset deve estar em formato de polígonos
# • data.yaml deve ter task: segment
# ========================================
