# ========================================
# YOLOv8m Training Configuration - TCC
# Detecção de Datas de Validade
# ========================================
# Hardware: GTX 1660 Super (6GB VRAM)
# Dataset: ~1000 imagens
# Tempo estimado: 8-9 horas
# ========================================
# ⚠️ ATENÇÃO: Modelo pesado! Use para resultados finais
# Recomendado: Treinar overnight ou em várias sessões
# ========================================

# Data configuration
data: config/yolo/bbox/data.yaml

# Model configuration
model: yolov8m.pt  # Medium - alto desempenho (25.9M parâmetros)
task: detect

# Training hyperparameters
epochs: 150    # Mais épocas para modelo maior convergir
imgsz: 640     # Resolução padrão YOLO
batch: 4       # Batch reduzido (CRÍTICO para não estourar VRAM)
device: 0      # GPU 0 (primeira GPU disponível)

# Learning rate schedule
lr0: 0.01      # Learning rate inicial
lrf: 0.01      # Learning rate final (fração do inicial)
momentum: 0.937
weight_decay: 0.0005

# Optimizer
optimizer: SGD  # SGD geralmente melhor que Adam para YOLO

# Training settings
patience: 50        # Early stopping após 50 épocas sem melhoria
workers: 4          # Reduzido de 8 para 4 (mais estável no Windows)
cache: false        # false = economia de RAM (importante para modelo pesado)
save: true          # Salvar checkpoints
save_period: 10     # Salvar a cada 10 épocas (backup para treino longo!)
exist_ok: true      # Sobrescrever experimentos anteriores

# Loss gains (pesos das losses)
box: 7.5   # Peso da loss de bounding box (detecção da região)
cls: 0.5   # Peso da loss de classificação (tipo de objeto)
dfl: 1.5   # Peso da loss de distribution focal (refinamento)

# Data augmentation (ATIVADO - essencial para generalização!)
augmentation: true

# Augmentations geométricas
hsv_h: 0.015        # Variação de matiz (hue) - pequena variação de cor
hsv_s: 0.7          # Variação de saturação - diferentes condições de luz
hsv_v: 0.4          # Variação de brilho (value) - iluminação variada
degrees: 10.0       # Rotação (±10 graus) - produtos em ângulos diferentes
translate: 0.1      # Translação (10% da imagem) - posição variada
scale: 0.5          # Zoom in/out (50%) - diferentes distâncias da câmera
shear: 0.0          # Cisalhamento (desabilitado - não útil para textos)
perspective: 0.0    # Distorção de perspectiva (desabilitado)
flipud: 0.0         # Flip vertical (0 = desabilitado - texto invertido)
fliplr: 0.5         # Flip horizontal (50% de chance - embalagens de ambos lados)

# Augmentations avançadas
mosaic: 1.0         # Mosaic augmentation (combina 4 imagens - 100%)
mixup: 0.1          # MixUp (mistura 2 imagens) - 10% de chance
copy_paste: 0.0     # Copy-paste augmentation (desabilitado)

# Validation settings
val: true           # Executar validação durante treinamento
plots: true         # Gerar plots de métricas (loss, precision, recall, etc)
rect: false         # Rectangular training (false = mais augmentation)

# Project settings
project: experiments                 # Pasta onde salvar resultados
name: yolov8m_validade_production   # Nome do experimento (produção)

# Inference settings (para depois do treino)
conf: 0.25          # Confidence threshold para predições
iou: 0.7            # IoU threshold para NMS (Non-Maximum Suppression)

# ========================================
# Notas para o TCC:
# ========================================
# 1. YOLOv8m = PRODUÇÃO (melhor precisão)
# 2. Tempo estimado: 8-9 horas (OVERNIGHT!)
# 3. Batch 4 (máximo para 6GB VRAM)
# 4. Checkpoints a cada 10 épocas (segurança)
# 5. Early stopping em 50 épocas
# 6. Use este para resultados FINAIS do TCC
#
# ⚠️ IMPORTANTE:
# - Monitore temperatura da GPU!
# - Deixe rodar overnight
# - Se crashar, retoma do último checkpoint
# - Batch 4 pode ser lento mas é SEGURO
#
# Vantagens:
# ✓ Melhor precisão (mAP)
# ✓ Detecta casos difíceis
# ✓ Menos falsos negativos
# ✓ Ideal para demonstração final
#
# Desvantagens:
# ✗ Treinamento muito lento
# ✗ Inferência mais lenta
# ✗ Risco de overfitting
# ✗ Alto uso de VRAM
#
# Para treinar:
# yolo train data=data.yaml model=yolov8m.pt cfg=yolov8m_config.yaml
#
# Para validar:
# yolo val data=data.yaml model=experiments/yolov8m_validade_production/weights/best.pt
#
# Para retomar treinamento (se crashar):
# yolo train resume model=experiments/yolov8m_validade_production/weights/last.pt
#
# 💡 DICA: Treine yolov8n primeiro para validar
# pipeline, depois yolov8s para comparação, e
# finalmente yolov8m para resultados finais!
# ========================================