name: ppro-openocr-minimal

steps:
  # 1. Apenas resize suave (OpenOCR precisa de tamanho mínimo)
  resize:
    enabled: true
    min_height: 48  # Menor que 64 - mais conservador
    min_width: 192
    maintain_aspect: true
    interpolation: lanczos  # Melhor que cubic para texto pequeno
  
  # 2. Deskew leve
  deskew:
    enabled: true
    method: contours
    max_angle: 360 
  
  # 3. Padding (só para evitar cortes)
  padding:
    enabled: true
    size: 10
    color: [255, 255, 255]
  
  # DESABILITAR tudo que modifica pixels:
  normalize_colors:
    enabled: false  # ❌ OpenOCR é treinado em imagens naturais
  
  clahe:
    enabled: false  # ❌ Amplifica ruído
  
  sharpen:
    enabled: false  # ❌ Cria artefatos
  
  denoise:
    enabled: false  # ❌ Borra detalhes
  
  grayscale:
    enabled: false  # ❌ OpenOCR usa RGB
  
  threshold:
    enabled: false  # ❌ Perde informação de cor/gradiente