# ⚙️ Pré-processamento OTIMIZADO para DATAS DE VALIDADE
# Focado em impressões térmicas, carimbos e textos em produtos
name: ppro-dates

steps:
  # 1. Normalização de cores (balancear sem distorcer)
  normalize_colors:
    enabled: true
    method: gray_world

  # 2. Resize (manter aspect ratio)
  resize:
    enabled: true
    min_height: 64
    min_width: 128
    maintain_aspect: true
    interpolation: cubic

  # 3. Grayscale (simplificar para focar em contraste)
  grayscale:
    enabled: true

  # 4. Deskew (corrigir rotação)
  deskew:
    enabled: true
    method: projection
    max_angle: 15

  # 5. CLAHE (aumentar contraste - CRUCIAL para datas desbotadas)
  clahe:
    enabled: true
    clip_limit: 2.5  # Balanceado para não criar granulação
    tile_grid_size: [8, 8]

  # 6. Denoise (remover ruído de textura)
  denoise:
    enabled: true
    method: bilateral
    d: 5
    sigma_color: 50
    sigma_space: 50

  # 7. Sharpen (melhorar definição de bordas)
  sharpen:
    enabled: true
    method: unsharp_mask
    strength: 1.0

  # 8. Threshold (binarização adaptativa)
  threshold:
    enabled: false  # Deixe False para PARSeq (precisa grayscale, não binário)
    method: adaptive_gaussian
    block_size: 11
    c: 2

  # 9. Padding (bordas para evitar cortes)
  padding:
    enabled: true
    size: 10
    color: 255  # Branco
