# ⚙️ Pré-processamento LEVE para DATAS DE VALIDADE
# Versão menos agressiva para preservar qualidade
name: ppro-dates-light

steps:
  # 1. Resize mínimo (apenas se muito pequeno)
  resize:
    enabled: true
    min_height: 32  # Mínimo para PARSeq
    min_width: 64
    maintain_aspect: true
    interpolation: cubic

  # 2. Grayscale
  grayscale:
    enabled: true

  # 3. Normalização suave de contraste
  clahe:
    enabled: true
    clip_limit: 1.5  # Mais suave que ppro-dates (era 2.5)
    tile_grid_size: [8, 8]

  # 4. Denoise muito suave (apenas ruído grosseiro)
  denoise:
    enabled: true
    method: bilateral
    d: 3  # Menor kernel (era 5)
    sigma_color: 30  # Mais conservador (era 50)
    sigma_space: 30

  # 5. Padding para evitar cortes
  padding:
    enabled: true
    size: 5  # Menor que ppro-dates (era 10)
    color: 255

  # Desabilitados para evitar destruir informação
  normalize_colors:
    enabled: false
  
  deskew:
    enabled: false
    
  sharpen:
    enabled: false
    
  threshold:
    enabled: false
