name: ppro-openocr-sharp-deblur

steps:
  # 1. Normalização suave de iluminação
  normalize_colors:
    enabled: true
    method: gray_world
  
  # 2. Resize MAIOR (OpenOCR funciona melhor com imagens grandes)
  resize:
    enabled: true
    min_height: 96
    min_width: 384
    max_height: 512
    max_width: 2048
    maintain_aspect: true
    interpolation: lanczos
  
  # 3. Deskew moderado
  deskew:
    enabled: true
    method: contours
    max_angle: 360
  
  # 4. CLAHE - DESABILITADO
  clahe:
    enabled: true
    clip_limit: 1.8
    tile_grid_size: [8, 8]
    color_space: lab
  
  deblur:
    enabled: true
    method: richardson_lucy  # 'wiener' (suave) ou 'richardson_lucy' (agressivo)
    kernel_size: 5  # Tamanho do kernel de desfoque estimado
    iterations: 10  # Número de iterações (apenas para richardson_lucy)
    snr: 25         # Signal-to-Noise Ratio (apenas para wiener)
  
  # 6. Sharpen FORTE (após deblur para aguçar bordas)
  sharpen:
    enabled: true
    method: unsharp_mask
    strength: 0.9
    radius: 1.2
    threshold: 1
  
  # 7. Denoising
  denoise:
    enabled: true
    method: bilateral
    d: 3
    sigma_color: 20
    sigma_space: 20
  
  # 8. Padding generoso
  padding:
    enabled: true
    size: 20
    color: [255, 255, 255]
  
  # DESABILITADOS
  grayscale:
    enabled: false
  
  threshold:
    enabled: false
  
  morphology:
    enabled: false

# ============================================================================
# NOVO: Técnicas de DEBLUR
# ============================================================================
# 
# 🔍 Métodos disponíveis:
# 
# 1. WIENER FILTER (recomendado para maioria dos casos)
#    - Suave, não cria artefatos
#    - Bom para desfoque moderado (motion blur, leve out-of-focus)
#    - Parâmetros: kernel_size (3-7), snr (15-50)
# 
# 2. RICHARDSON-LUCY DECONVOLUTION (para desfoque severo)
#    - Mais agressivo, pode criar halos se mal configurado
#    - Excelente para out-of-focus severo
#    - Parâmetros: kernel_size (5-11), iterations (5-30)
# 
# 3. BLIND DECONVOLUTION (futuro - estima kernel automaticamente)
#    - Mais lento mas não precisa saber tipo de desfoque
# 
# ============================================================================
# CONFIGURAÇÕES POR CENÁRIO:
# ============================================================================
# 
# 📷 DESFOQUE LEVE (foto tremida, câmera instável):
# deblur:
#   method: wiener
#   kernel_size: 3
#   snr: 30
# 
# 📷 DESFOQUE MODERADO (motion blur, out-of-focus leve):
# deblur:
#   method: wiener
#   kernel_size: 5
#   snr: 25
# 
# 📷 DESFOQUE SEVERO (muito fora de foco):
# deblur:
#   method: richardson_lucy
#   kernel_size: 7
#   iterations: 15
# 
# 📷 DESFOQUE MISTO (alguns crops nítidos, outros borrados):
# deblur:
#   method: wiener
#   kernel_size: 5
#   snr: 25
#   adaptive: true  # Aplica só se detectar blur (futuro)
# 
# ============================================================================