# ========================================
# 🔧 Configuração Principal - Datalid 3.0
# ========================================

# Informações do Projeto
project:
  name: datalid
  version: 3.0.0
  description: "Sistema de Detecção de Datas de Validade com Segmentação Poligonal"
  author: "TCC - Projeto Transformador II"
  
# Configuração de Caminhos
paths:
  data_dir: data
  raw_data: data/raw
  processed_data: data/processed
  models_dir: models
  experiments_dir: experiments
  config_dir: config
  scripts_dir: scripts
  src_dir: src
  outputs_dir: outputs

# Configuração de Dados
data:
  # Divisão de dados (train/val/test)
  splits:
    train: 0.7
    val: 0.2
    test: 0.1
  
  # Seed para reprodutibilidade
  random_seed: 42
  
  # Classes do projeto
  classes:
    - exp_date
  
  num_classes: 1
  
  # Formatos de imagem suportados
  image_extensions:
    - .jpg
    - .jpeg
    - .png
  
  # Formatos de label suportados
  label_extensions:
    - .txt
    - .json
    - .xml

# Configuração de Processamento
processing:
  # Modo de cópia de arquivos
  copy_mode: copy  # copy, move, symlink
  
  # Validação automática
  auto_validate: true
  
  # Mostrar preview antes de processar
  show_preview: false
  
  # Tipo de tarefa padrão
  default_task: segment  # segment, detect, both
  
  # Ignorar labels vazios
  ignore_empty_labels: true
  
  # Threshold mínimo de objetos por label
  min_objects_per_label: 1

# Configuração do Roboflow
roboflow:
  api_key: crS7dKMHZj3VlfWw40mS
  workspace: projetotransformadorii
  project: tcc_dateset_v2-zkcsu
  version: 2
  format: yolov8
  
# Configuração de Treinamento (Padrões)
training:
  # Tarefa padrão
  default_task: segment  # segment ou detect
  
  # Device
  device: 0  # 0 para GPU, cpu para CPU
  
  # Configurações gerais
  patience: 50
  save_period: 10
  verbose: true
  
  # Métricas
  metrics:
    - precision
    - recall
    - mAP50
    - mAP50-95
  
  # Augmentations (padrão)
  augmentation:
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
  
  # Otimizador
  optimizer:
    name: SGD
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
  
  # Presets de treinamento
  presets:
    quick_test:
      epochs: 10
      batch: 16
      imgsz: 640
      name: quick_test
    
    development:
      epochs: 50
      batch: 8
      imgsz: 640
      name: dev
    
    final:
      epochs: 150
      batch: 8
      imgsz: 640
      name: final
    
    overnight:
      epochs: 200
      batch: 4
      imgsz: 640
      name: overnight

# Configuração de Validação
validation:
  # Threshold de confiança
  conf_threshold: 0.25
  
  # IoU threshold para NMS
  iou_threshold: 0.45
  
  # Máximo de detecções por imagem
  max_det: 300
  
  # Salvar visualizações
  save_plots: true
  save_json: true
  save_txt: true

# Configuração de API
api:
  host: 0.0.0.0
  port: 8000
  reload: true
  workers: 4
  log_level: info

# Configuração de Logging
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  to_file: true
  file_path: logs/datalid.log
  rotation: "10 MB"
  retention: "1 week"

# Configuração de Experimentos
experiments:
  # Diretório base
  base_dir: experiments
  
  # Salvar pesos
  save_weights: true
  save_best_only: false
  
  # TensorBoard
  tensorboard:
    enabled: true
    port: 6006
  
  # Tracking de métricas
  track_metrics: true
  
  # Comparação de modelos
  compare_on_finish: false

# Configuração de Recursos
resources:
  # GPU
  use_gpu: true
  gpu_memory_fraction: 0.9
  
  # CPU
  num_workers: 4
  prefetch_factor: 2
  
  # Cache
  use_cache: false
  cache_dir: .cache

# Configuração de Visualização
visualization:
  # Cores para classes (RGB)
  class_colors:
    exp_date: [255, 0, 0]  # Vermelho
  
  # Espessura de linhas
  line_thickness: 2
  
  # Tamanho de fonte
  font_scale: 0.5
  
  # Transparência de máscaras
  mask_alpha: 0.3
  
  # DPI para salvar imagens
  dpi: 100

# Configuração de Produção
production:
  # Modelo padrão para deploy
  default_model: yolov8s-seg
  
  # Threshold de confiança
  conf_threshold: 0.5
  
  # Processar em lote
  batch_processing: true
  batch_size: 8
  
  # Salvar resultados
  save_results: true
  results_dir: outputs/predictions
