# ========================================
# 🔧 Configuração Central do Projeto Datalid 3.0
# Detecção de Datas de Validade
# ========================================

# Informações do Projeto
project:
  name: "Datalid"
  version: "3.0.0"
  description: "Sistema de Detecção de Datas de Validade"
  author: "TCC - Projeto Transformador II"
  license: "CC BY 4.0"

# ========================================
# CAMINHOS DO PROJETO
# ========================================
paths:
  data_dir: "data"
  raw_data: "data/raw"
  processed_data: "data/processed"
  config_dir: "config"
  experiments_dir: "experiments"
  models_dir: "models"
  outputs_dir: "outputs"
  scripts_dir: "scripts"
  src_dir: "src"

# ========================================
# CONFIGURAÇÕES DE DATASET
# ========================================
dataset:
  # Divisão padrão dos dados
  splits:
    train: 0.7      # 70% para treinamento
    val: 0.2        # 20% para validação
    test: 0.1       # 10% para teste

  # Presets de divisão alternativos
  split_presets:
    balanced:
      train: 0.6
      val: 0.2
      test: 0.2
    research:
      train: 0.8
      val: 0.1
      test: 0.1
    production:
      train: 0.7
      val: 0.3
      test: 0.0
    quick_test:
      train: 0.5
      val: 0.25
      test: 0.25

  # Formatos suportados
  image_formats: [".jpg", ".jpeg", ".png", ".bmp", ".tiff"]
  label_formats: [".txt", ".json", ".xml"]

  # Classes do dataset
  classes:
    0: "exp_date"
  num_classes: 1

  # Tamanho padrão de imagem
  default_image_size: 640

# ========================================
# CONFIGURAÇÕES DE ROBOFLOW
# ========================================
roboflow:
  api_key: "crS7dKMHZj3VlfWw40mS"
  workspace: "projetotransformadorii"
  project: "tcc_dateset_v2-zkcsu"
  version: 2
  format: "yolov8"
  url: "https://universe.roboflow.com/projetotransformadorii/tcc_dateset_v2-zkcsu"

# ========================================
# CONFIGURAÇÕES DE HARDWARE
# ========================================
hardware:
  # Hardware padrão do projeto
  default:
    name: "GTX 1660 Super"
    vram: 6  # GB
    recommended_batch:
      detect_nano: 32
      detect_small: 16
      detect_medium: 8
      segment_nano: 16
      segment_small: 8
      segment_medium: 4

  # Presets para diferentes hardwares
  presets:
    gtx1660s:
      name: "GTX 1660 Super"
      vram: 6
      device: "0"
      workers: 4
      cache: false
    rtx3060:
      name: "RTX 3060"
      vram: 12
      device: "0"
      workers: 8
      cache: true
    rtx4060:
      name: "RTX 4060"
      vram: 16
      device: "0"
      workers: 8
      cache: true
    cpu:
      name: "CPU Only"
      vram: 0
      device: "cpu"
      workers: 2
      cache: false

# ========================================
# CONFIGURAÇÕES DE TREINAMENTO PADRÃO
# ========================================
training:
  # Configurações globais
  default_task: "segment"  # Foco em segmentação poligonal
  default_model_size: "small"
  
  # Épocas padrão por cenário
  epochs:
    quick_test: 10
    development: 50
    baseline: 100
    recommended: 120
    production: 150
    overnight: 200

  # Configurações de otimização
  optimizer:
    type: "SGD"
    learning_rate:
      initial: 0.01
      final: 0.01
    momentum: 0.937
    weight_decay: 0.0005

  # Early stopping
  patience:
    quick: 20
    normal: 50
    extended: 100

  # Checkpoints
  save_checkpoints: true
  save_period: 10  # Salvar a cada N épocas
  save_best_only: false

  # Validação
  validate_during_training: true
  generate_plots: true
  rectangular_training: false

  # Loss weights
  loss_gains:
    box: 7.5
    cls: 0.5
    dfl: 1.5

# ========================================
# CONFIGURAÇÕES DE DATA AUGMENTATION
# ========================================
augmentation:
  # Controle global
  enabled: true

  # Presets de augmentation
  presets:
    disabled:
      enabled: false
    
    light:
      enabled: true
      hsv_h: 0.005
      hsv_s: 0.3
      hsv_v: 0.2
      degrees: 5.0
      translate: 0.05
      scale: 0.3
      fliplr: 0.3
      mosaic: 0.5
      mixup: 0.0
    
    medium:  # Padrão recomendado
      enabled: true
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      degrees: 10.0
      translate: 0.1
      scale: 0.5
      shear: 0.0
      perspective: 0.0
      flipud: 0.0
      fliplr: 0.5
      mosaic: 1.0
      mixup: 0.1
      copy_paste: 0.0
    
    heavy:
      enabled: true
      hsv_h: 0.02
      hsv_s: 0.9
      hsv_v: 0.5
      degrees: 15.0
      translate: 0.15
      scale: 0.7
      fliplr: 0.5
      mosaic: 1.0
      mixup: 0.2
      copy_paste: 0.1

  # Configuração padrão (medium)
  default:
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 10.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0  # Desabilitado para texto
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.1
    copy_paste: 0.0

# ========================================
# CONFIGURAÇÕES DE INFERÊNCIA/DETECÇÃO
# ========================================
inference:
  # Thresholds padrão
  confidence_threshold: 0.25
  iou_threshold: 0.7
  max_detections: 1000

  # Configurações de NMS (Non-Maximum Suppression)
  nms:
    enabled: true
    agnostic: false

# ========================================
# CONFIGURAÇÕES DE OCR
# ========================================
ocr:
  engine: "tesseract"  # tesseract, easyocr, paddleocr
  languages: ["por", "eng"]  # Português e Inglês
  confidence_threshold: 0.6
  
  # Configurações específicas do Tesseract
  tesseract:
    config: "--psm 6 --oem 3"
    whitelist: "0123456789/"
  
  # Pré-processamento de imagem
  preprocessing:
    resize: true
    denoise: true
    threshold: true
    contrast_enhancement: true

# ========================================
# CONFIGURAÇÕES DE API
# ========================================
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  max_file_size: 10485760  # 10MB em bytes
  allowed_extensions: [".jpg", ".jpeg", ".png"]
  
  # Configurações de CORS
  cors:
    enabled: true
    origins: ["*"]
    methods: ["GET", "POST"]
    headers: ["*"]

# ========================================
# CONFIGURAÇÕES DE LOGGING
# ========================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  
  # Arquivos de log
  files:
    enabled: true
    rotation: "1 week"
    retention: "1 month"
    compression: "zip"

# ========================================
# CONFIGURAÇÕES DE EXPERIMENTOS
# ========================================
experiments:
  # Nomeação automática
  auto_naming: true
  naming_pattern: "{model}_{task}_{timestamp}"
  
  # Tracking
  track_metrics: true
  save_metrics: true
  
  # Comparação
  comparison_metrics: ["mAP50", "mAP50-95", "precision", "recall", "f1"]

# ========================================
# CONFIGURAÇÕES DE VALIDAÇÃO
# ========================================
validation:
  # Validação automática
  validate_before_training: false
  validate_after_processing: true
  
  # Métricas mínimas esperadas (alertas)
  minimum_metrics:
    images_per_split:
      train: 100
      val: 20
      test: 10
    labels_coverage: 0.95  # 95% das imagens devem ter labels

# ========================================
# CONFIGURAÇÕES DE PRODUÇÃO
# ========================================
production:
  # Modelo recomendado para produção
  recommended_model: "yolov8s-seg"
  
  # Otimizações
  use_half_precision: false  # FP16
  use_quantization: false
  
  # Deployment
  export_formats: ["onnx", "torchscript"]
  optimization_level: 2

# ========================================
# NOTAS E DOCUMENTAÇÃO
# ========================================
notes:
  - "Foco principal: SEGMENTAÇÃO POLIGONAL"
  - "Dataset: ~1000 imagens de produtos com datas de validade"
  - "Hardware padrão: GTX 1660 Super (6GB VRAM)"
  - "Todas as configurações podem ser sobrescritas via CLI ou arquivos específicos"
  - "Arquivos YAML em config/yolo/ têm precedência sobre estas configurações"
