date_parser:
  date_formats:
    - '%d/%m/%Y'
    - '%d/%m/%y'
    - '%d.%m.%Y'
    - '%d-%m-%Y'
    - '%Y-%m-%d'
    - '%d%m%Y'
  
  validation:
    min_year: 2024
    max_year: 2035
    allow_past: true
  
  corrections:
    enabled: true
    fuzzy_threshold: 0.75  # 75%+ similaridade para fuzzy match
    common_errors:
      O: '0'
      I: '1'
      ':': '/'
      '\\': '/'