# 🎯 Enhanced PARSeq Configuration
# Configuração completa para pipeline de OCR otimizado

# ============================================================================
# MODELO PARSEQ
# ============================================================================
model:
  model_name: parseq_patch16_224  # Opções: parseq_tiny, parseq, parseq_patch16_224
  device: cuda  # cuda ou cpu
  img_height: 32
  img_width: 128
  max_length: 25
  batch_size: 1

# ============================================================================
# PIPELINE - Habilitar/Desabilitar Componentes
# ============================================================================
pipeline:
  enable_line_detection: true
  enable_geometric_norm: true
  enable_photometric_norm: true
  enable_ensemble: true
  ensemble_strategy: rerank  # confidence, voting, rerank

# ============================================================================
# LINE DETECTOR - Detecção e Splitting de Linhas
# ============================================================================
line_detector:
  method: hybrid  # projection, clustering, morphology, hybrid
  min_line_height: 10
  max_line_gap: 5
  dbscan_eps: 15
  min_component_width: 5
  morphology_kernel_width: 50
  
  # Novos parâmetros de rotação
  enable_rotation_detection: true
  max_rotation_angle: 5.0  # Graus - limite seguro
  
  # Método de clustering
  clustering_method: dbscan  # dbscan ou agglomerative

# ============================================================================
# GEOMETRIC NORMALIZER - Normalização Geométrica
# ============================================================================
geometric_normalizer:
  enable_deskew: true
  max_angle: 10  # Ângulo máximo para correção (graus)
  
  # Perspective warp (use com cautela)
  enable_perspective: false  # Geralmente muito agressivo
  
  # Resize
  target_heights: [32, 64, 128]  # Alturas para variantes
  maintain_aspect: true

# ============================================================================
# PHOTOMETRIC NORMALIZER - Normalização Fotométrica
# ============================================================================
photometric_normalizer:
  # Denoise
  denoise_method: bilateral  # median, bilateral, none
  
  # Shadow removal
  shadow_removal: true
  shadow_ksize: 21  # Tamanho do kernel (deve ser ímpar)
  
  # CLAHE (Contrast Limited Adaptive Histogram Equalization)
  clahe_enabled: true
  clahe_clip_limit: 1.5  # 1.0-3.0, recomendado 1.2-1.6
  clahe_tile_grid: [8, 8]  # (4,4) ou (8,8) para texto
  
  # Sharpen
  sharpen_enabled: true
  sharpen_strength: 0.3  # 0.0-1.0

# ============================================================================
# POSTPROCESSOR - Pós-processamento Contextual
# ============================================================================
postprocessor:
  # Normalização básica
  uppercase: true
  remove_symbols: false  # Cuidado: pode remover caracteres válidos
  
  # Mapeamento de ambiguidades
  ambiguity_mapping: true
  
  # Correção de formatos conhecidos
  fix_formats: true
  
  # Fuzzy matching (requer python-Levenshtein)
  enable_fuzzy_match: true
  fuzzy_threshold: 2  # Distância máxima de edição
  
  # Palavras conhecidas para fuzzy matching
  known_words:
    - LOT
    - LOTE
    - DATE
    - DATA
    - BATCH
    - MFG
    - EXP
    - FABRICAÇÃO
    - VALIDADE
    - PRODUTO
    - PRODUCT
  
  # Formatos esperados (regex)
  expected_formats:
    - 'LOT[EO]?\s*\.?\s*\d+'  # LOTE 123, LOT.123
    - '\d{1,2}[/-]\d{1,2}[/-]\d{2,4}'  # Datas
    - '[A-Z]{2,}\s*\d+'  # Códigos alfanuméricos

# ============================================================================
# PRESETS POR TIPO DE IMAGEM
# ============================================================================
# Descomente o preset desejado e copie para as seções acima

# PRESET 1: Imagens de Alta Qualidade
# preset_high_quality:
#   pipeline:
#     enable_line_detection: true
#     enable_geometric_norm: true
#     enable_photometric_norm: false
#     enable_ensemble: false

# PRESET 2: Imagens com Sombras/Iluminação Irregular
# preset_shadows:
#   photometric_normalizer:
#     denoise_method: bilateral
#     shadow_removal: true
#     clahe_enabled: true
#     clahe_clip_limit: 1.6
#     clahe_tile_grid: [8, 8]

# PRESET 3: Imagens com Rotação/Perspectiva
# preset_rotation:
#   line_detector:
#     enable_rotation_detection: true
#     max_rotation_angle: 10.0
#   geometric_normalizer:
#     enable_deskew: true
#     max_angle: 15

# PRESET 4: Imagens Difíceis (Recomendado para Máxima Acurácia)
# preset_difficult:
#   pipeline:
#     enable_line_detection: true
#     enable_geometric_norm: true
#     enable_photometric_norm: true
#     enable_ensemble: true
#     ensemble_strategy: rerank
#   photometric_normalizer:
#     clahe_clip_limit: 1.8
#     sharpen_enabled: true
#     sharpen_strength: 0.5
#   line_detector:
#     method: hybrid
#     clustering_method: agglomerative

# ============================================================================
# EXPERIMENTAÇÃO - Configurações de Teste
# ============================================================================
experiment:
  output_dir: outputs/experiments
  save_visualizations: true
  save_intermediate_results: false
  
  # Métricas a calcular
  calculate_cer: true
  calculate_wer: true
  calculate_exact_match: true
  calculate_line_ordering_errors: false

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  log_file: outputs/enhanced_parseq.log
  log_rotation: 10 MB
  
  # Verbose output
  verbose_preprocessing: false
  verbose_reranking: true
  verbose_postprocessing: false
