# PARSeq BASE - Modelo Balanceado (Recomendado para multi-linha)
engine: parseq

# Modelo BASE (60MB)
model_name: 'parseq'  # Melhor balanceamento entre velocidade e precisão

# Device
device: 'cuda'  # ou 'cpu'

# Configuração de imagem
img_height: 32
img_width: 128
max_length: 25

# Batch processing
batch_size: 1

# Thresholds
confidence_threshold: 0.7

# Preprocessing (usa configuração específica para PARSeq)
preprocessing: ppro-parseq

# Output
save_preprocessed: false
save_text_output: true
verbose: true
