# PARSeq OCR específico (Permutation Auto-regressive Sequence)
engine: parseq

# =============================================================================
# 🎯 ESCOLHA DO MODELO (importante para multi-linha!)
# =============================================================================
# Modelos disponíveis (do mais leve ao mais pesado):
#
# 1. parseq_tiny (ou parseq-tiny, tiny)
#    - Tamanho: ~20MB
#    - Velocidade: Muito rápida (10-20ms/imagem GPU)
#    - Precisão: Boa para texto simples de 1 linha
#    - Recomendado: Produção com texto curto e simples
#    - ⚠️ LIMITAÇÃO: Pode ter dificuldade com MULTI-LINHA
#
# 2. parseq (ou parseq-base, base)
#    - Tamanho: ~60MB
#    - Velocidade: Média (30-50ms/imagem GPU)
#    - Precisão: Muito boa, lida melhor com multi-linha
#    - Recomendado: ✅ MELHOR CUSTO-BENEFÍCIO para multi-linha
#
# 3. parseq_patch16_224 (ou parseq-large, large)
#    - Tamanho: ~100MB
#    - Velocidade: Mais lenta (50-100ms/imagem GPU)
#    - Precisão: Excelente, ideal para textos complexos
#    - Recomendado: Máxima precisão, textos difíceis
#
# =============================================================================

# ⭐ CONFIGURAÇÃO ATUAL
# Para dataset com multi-linha (2+ linhas), use 'parseq' ou 'parseq_patch16_224'
model_name: 'parseq'  # Alterado de parseq_tiny para parseq (melhor para multi-linha)

# Alternativas (descomente para testar):
# model_name: 'parseq_tiny'          # Mais rápido, mas pior em multi-linha
# model_name: 'parseq_patch16_224'   # Melhor precisão, mas mais lento

# Device
device: 'cuda'  # ou 'cpu'

# Configuração de imagem
img_height: 32
img_width: 128
max_length: 25

# Batch processing
batch_size: 1

# Thresholds
confidence_threshold: 0.7

# Preprocessing (usa configuração específica para PARSeq)
preprocessing: ppro-parseq

# Output
save_preprocessed: false
save_text_output: true
verbose: true
