# ========================================
# Enhanced PARSeq - OTIMIZADO PARA DATAS DE VALIDADE
# Configuração específica para reconhecimento de datas em produtos
# ========================================

name: parseq_enhanced_dates

# Preset ativo (sobrescreve configurações abaixo)
# Opções: 'dates_fast', 'dates_balanced', 'dates_high_quality', null
active_preset: dates_balanced  # null para usar config manual

# ========================================
# MODELO BASE - OTIMIZADO PARA DATAS
# ========================================
model_name: parseq_patch16_224  # 'parseq_tiny' (rápido), 'parseq' (balanceado), 'parseq_patch16_224' (preciso)
device: cuda  # 'cuda' ou 'cpu'

# OTIMIZADO: Tamanho compatível com modelo treinado
img_height: 32   # ✅ Modelo parseq OBRIGATORIAMENTE usa 32
img_width: 128   # ✅ Modelo parseq OBRIGATORIAMENTE usa 128

max_length: 25
batch_size: 1

# ========================================
# PIPELINE FEATURES
# ========================================
enable_line_detection: true     # Detectar múltiplas linhas (LOT + DATE)
enable_geometric_norm: true     # Correção de rotação/perspectiva
enable_photometric_norm: true   # Melhorar contraste/iluminação
enable_ensemble: true           # Usar variantes para maior precisão
enable_postprocessing: true     # Correções contextuais

ensemble_strategy: rerank  # 'confidence', 'voting', 'rerank'

# ========================================
# LINE DETECTOR
# ========================================
line_detector:
  method: hybrid  # 'projection', 'clustering', 'morphology', 'hybrid'
  min_line_height: 15  # Aumentado para datas (textos maiores que códigos)
  max_line_gap: 8
  dbscan_eps: 20
  min_component_width: 10
  morphology_kernel_width: 50
  filter_noise: true
  min_char_count: 3  # Mínimo 3 caracteres (ex: "VAL")

# ========================================
# GEOMETRIC NORMALIZER
# ========================================
geometric_normalizer:
  enable_deskew: true
  max_angle: 15  # Datas podem estar mais inclinadas em produtos
  deskew_method: hough  # 'hough', 'moments', 'projection'
  enable_perspective: true  # Importante para produtos curvos
  target_heights: [32, 48, 64]  # Alturas otimizadas para datas
  maintain_aspect: true
  add_padding: true
  padding_ratio: 0.15  # Mais padding para evitar cortes

# ========================================
# PHOTOMETRIC NORMALIZER - OTIMIZADO PARA IMPRESSÃO TÉRMICA
# ========================================
photometric_normalizer:
  # Denoise (remover ruído de textura do produto)
  denoise_method: bilateral  # 'median', 'bilateral', 'none'
  bilateral_d: 5
  bilateral_sigma_color: 50
  bilateral_sigma_space: 50
  
  # Shadow removal (datas podem estar em áreas sombreadas)
  shadow_removal: true
  shadow_kernel_size: 15
  
  # CLAHE (aumentar contraste - crucial para datas desbotadas)
  clahe_enabled: true
  clahe_clip_limit: 3.0  # Aumentado de 1.5 para datas com baixo contraste
  clahe_tile_grid: [8, 8]
  
  # Sharpening (datas podem estar borradas)
  sharpen_enabled: true
  sharpen_strength: 1.5  # Aumentado de 0.3
  
  # Auto-invert (se data estiver em fundo escuro)
  auto_invert: true

# ========================================
# ENSEMBLE & RERANKING - OTIMIZADO PARA DATAS
# ========================================
ensemble:
  num_variants: 4  # Aumentado de 3 para maior cobertura
  variant_types:
    - height       # Diferentes alturas
    - clahe        # Diferentes níveis de contraste
    - denoise      # Com/sem denoise
    - sharpen      # Com/sem sharpening
  
  reranker:
    method: weighted
    weights:
      confidence: 0.30        # Reduzido (pode estar errada com alta confiança)
      length_ratio: 0.10      # Comprimento esperado
      dict_match: 0.20        # Match com palavras-chave
      consensus: 0.15         # Acordo entre variantes
      date_format: 0.25       # NOVO: Match com formato de data (mais importante)
    
    # Palavras-chave esperadas em datas de validade
    expected_terms:
      - "LOTE"
      - "LOT"
      - "L"
      - "VALIDADE"
      - "VAL"
      - "EXP"
      - "EXPIRY"
      - "FAB"
      - "MFG"
      - "FABRICACAO"
      - "USE BY"
      - "BEST BEFORE"
    
    # Padrões esperados para datas
    expected_patterns:
      # Datas com separadores
      - '\d{1,2}[/\-\.]\d{1,2}[/\-\.]\d{2,4}'  # DD/MM/YYYY, DD-MM-YY
      # Datas sem separadores
      - '\d{6,8}'  # DDMMYYYY, DDMMYY
      # Lote
      - 'L[OT]*\s*\.?\s*[A-Z0-9]+'
      - 'LOTE\s*\.?\s*[A-Z0-9]+'
      # Validade
      - 'VAL[IDADE]*\s*\.?\s*\d'
      - 'EXP[IRY]*\s*\.?\s*\d'

# ========================================
# CONTEXTUAL POSTPROCESSOR - OTIMIZADO PARA DATAS
# ========================================
postprocessor:
  uppercase: false  # NÃO forçar uppercase (datas são números)
  remove_symbols: false  # NÃO remover separadores (/, -, .)
  trim_whitespace: true
  
  # Correção de ambiguidades (CRUCIAL para datas)
  ambiguity_mapping: true
  ambiguity_rules:
    - ['O', '0', 'always']  # O sempre vira 0 em datas
    - ['o', '0', 'always']
    - ['I', '1', 'always']  # I sempre vira 1
    - ['l', '1', 'always']  # l sempre vira 1
    - ['|', '1', 'always']  # pipe vira 1
    - ['S', '5', 'context'] # S vira 5 em contexto numérico
    - ['s', '5', 'context']
    - ['B', '8', 'context'] # B vira 8 em contexto numérico
    - ['b', '8', 'context']
    - ['Z', '2', 'context'] # Z vira 2
    - ['z', '2', 'context']
    - ['G', '6', 'context'] # G vira 6
    - ['g', '6', 'context']
    - ['Q', '0', 'context'] # Q vira 0
    - ['q', '0', 'context']
  
  # Validação de formatos
  fix_formats: true
  expected_formats:
    # Datas (prioridade ALTA)
    - pattern: '\d{2}[/\-\.]\d{2}[/\-\.]\d{4}'
      example: "25/10/2025"
      priority: high
      
    - pattern: '\d{2}[/\-\.]\d{2}[/\-\.]\d{2}'
      example: "25/10/25"
      priority: high
      
    - pattern: '\d{8}'
      example: "25102025"
      priority: high
      
    - pattern: '\d{6}'
      example: "251025"
      priority: high
    
    # Lote (prioridade MÉDIA)
    - pattern: 'L[OT]*\s*\.?\s*[A-Z0-9]+'
      example: "LOT 12345"
      priority: medium
      
    - pattern: 'LOTE\s*\.?\s*[A-Z0-9]+'
      example: "LOTE 12345"
      priority: medium
    
    # Validade (prioridade MÉDIA)
    - pattern: 'VAL[IDADE]*\s*\.?\s*\d'
      example: "VAL 25/10/2025"
      priority: medium
  
  # Fuzzy matching (para palavras-chave mal escritas)
  fuzzy_matching: true
  fuzzy_threshold: 0.75  # Reduzido de 0.8 (ser mais tolerante)
  fuzzy_dict:
    - "LOTE"
    - "LOT"
    - "VALIDADE"
    - "VAL"
    - "EXPIRY"
    - "EXP"
    - "FABRICACAO"
    - "FAB"
    - "MFG"
  
  # Correções específicas do domínio
  domain_corrections:
    enabled: true
    rules:
      # Correções comuns em LOT
      - from: "L0TE"
        to: "LOTE"
      - from: "LOT3"
        to: "LOTE"
      - from: "L0T"
        to: "LOT"
      
      # Correções comuns em VAL
      - from: "VAL1DADE"
        to: "VALIDADE"
      - from: "VAL1D"
        to: "VALID"
      - from: "EXP1RY"
        to: "EXPIRY"
      
      # Correções comuns em FAB
      - from: "FA8"
        to: "FAB"
      - from: "F48"
        to: "FAB"

# ========================================
# PÓS-PROCESSAMENTO ADICIONAL PARA DATAS
# ========================================
postprocessing:
  # Extrair apenas data ou incluir lote?
  extract_date_only: false  # false = incluir lote também
  
  # Estruturar saída (LOT: xxx DATE: xxx)
  extract_structured: true
  
  # Validar se data é válida (dia <= 31, mês <= 12, etc)
  validate_date_logic: true
  
  # Normalizar formato de data
  normalize_date_format: false  # false = manter formato original
  output_date_format: "DD/MM/YYYY"  # se normalize_date_format = true

# ========================================
# EVALUATION
# ========================================
evaluation:
  metrics:
    - cer              # Character Error Rate
    - wer              # Word Error Rate
    - accuracy         # Exact Match
    - confidence       # Confiança média
    - date_accuracy    # NOVO: Accuracy específica para datas
  
  error_analysis:
    enabled: true
    output_dir: "outputs/error_analysis"
    categorize_errors: true
    error_categories:
      - digit_confusion      # 0/O, 1/I/l
      - separator_missing    # 25102025 vs 25/10/2025
      - partial_recognition  # Só reconheceu parte
      - format_wrong         # Formato incorreto
  
  compare_baseline: true
  baseline_engine: "paddleocr"  # Comparar com PaddleOCR

# ========================================
# LOGGING
# ========================================
logging:
  level: INFO  # DEBUG para mais detalhes
  verbose: true
  show_progress: true
  save_visualizations: true
  viz_output_dir: "outputs/visualizations/dates"
  log_variants: true  # Log cada variante do ensemble

# ========================================
# PERFORMANCE
# ========================================
performance:
  num_workers: 4
  cache_preprocessed: true
  cache_dir: "cache/parseq_dates"
  batch_inference: true
  optimal_batch_size: 4  # Reduzido (imagens maiores 64x256)

# ========================================
# PRESETS (Configurações Pré-definidas)
# ========================================
presets:
  # Modo rápido para datas (testes)
  dates_fast:
    model_name: parseq_tiny
    img_height: 48
    img_width: 192
    enable_line_detection: true
    enable_geometric_norm: true
    enable_photometric_norm: false
    enable_ensemble: false
    enable_postprocessing: true
  
  # Modo balanceado para datas (RECOMENDADO)
  dates_balanced:
    model_name: parseq
    img_height: 32
    img_width: 128
    enable_line_detection: true
    enable_geometric_norm: true
    enable_photometric_norm: true
    enable_ensemble: true
    enable_postprocessing: true
    ensemble:
      num_variants: 4
    photometric_normalizer:
      clahe_clip_limit: 3.0
      sharpen_enabled: true
      sharpen_strength: 1.5
  
  # Modo máxima qualidade para datas (mais lento)
  dates_high_quality:
    model_name: parseq_patch16_224
    img_height: 96
    img_width: 384
    enable_line_detection: true
    enable_geometric_norm: true
    enable_photometric_norm: true
    enable_ensemble: true
    enable_postprocessing: true
    ensemble:
      num_variants: 6
      variant_types:
        - height
        - clahe
        - denoise
        - sharpen
        - blur
        - threshold
    photometric_normalizer:
      clahe_clip_limit: 4.0
      sharpen_enabled: true
      sharpen_strength: 2.0
  
  # Modo thermal (para impressão térmica desbotada)
  dates_thermal:
    model_name: parseq
    img_height: 64
    img_width: 256
    enable_line_detection: true
    enable_geometric_norm: true
    enable_photometric_norm: true
    enable_ensemble: true
    enable_postprocessing: true
    photometric_normalizer:
      denoise_method: bilateral
      clahe_enabled: true
      clahe_clip_limit: 5.0  # Muito agressivo para thermal desbotada
      sharpen_enabled: true
      sharpen_strength: 2.5
      auto_invert: true
    ensemble:
      num_variants: 5
  
  # Modo stamp (para carimbos/tinta)
  dates_stamp:
    model_name: parseq
    img_height: 64
    img_width: 256
    enable_line_detection: true
    enable_geometric_norm: true
    enable_photometric_norm: true
    enable_ensemble: true
    enable_postprocessing: true
    photometric_normalizer:
      denoise_method: median
      clahe_enabled: true
      clahe_clip_limit: 2.5
      sharpen_enabled: false  # Carimbos já são nítidos
      auto_invert: true
    ensemble:
      num_variants: 3
  
  # Modo ablation (para estudos)
  dates_ablation:
    run_all_combinations: true
    test_features:
      - line_detection
      - geometric_norm
      - photometric_norm
      - ensemble
      - postprocessing

# ========================================
# PRÉ-PROCESSAMENTO RECOMENDADO
# ========================================
preprocessing: "ppro-dates"  # Ver config/preprocessing/ppro-dates.yaml