# PARSeq LARGE - Modelo de Alta Precisão (Melhor para textos complexos)
engine: parseq

# Modelo LARGE (100MB) - Máxima precisão
model_name: 'parseq_patch16_224'  # Melhor para multi-linha e textos complexos

# Device
device: 'cuda'  # ou 'cpu'

# Configuração de imagem (LARGE usa 224x224 em vez de 32x128!)
img_height: 224
img_width: 224
max_length: 25

# Batch processing
batch_size: 1

# Thresholds
confidence_threshold: 0.7

# Preprocessing (usa configuração específica para PARSeq)
preprocessing: ppro-parseq

# Output
save_preprocessed: false
save_text_output: true
verbose: true
